Weighted Reservoir Sampling accumulator
3Hren/metrics pull request #13
Opened 2017-03-01 17:43 UTC by karitra

Weighted Reservoir Sampling for exponentially decaying accumulator, based on:
 * [dropwizard.metrics](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java)
 * [_Cormode et al. Forward Decay: A Practical Time Decay Model for Streaming Systems. ICDE '09: Proceedings of the 2009 IEEE International Conference on Data Engineering (2009)_](http://dimacs.rutgers.edu/~graham/pubs/papers/fwddecay.pdf)

**Still WIP**

2017-03-03 11:26 UTC, karitra commented
@3Hren , @antmat PTAL

2017-03-03 14:30 UTC, 3Hren requested changes

2017-03-03 14:30 UTC, 3Hren commented on include/metrics/accumulator/decaying/exponentially.hpp
> +#include <metrics/accumulator/snapshot/weighted.hpp>
s/<>/"

2017-03-03 14:30 UTC, 3Hren commented on include/metrics/accumulator/decaying/exponentially.hpp
> +    typedef std::chrono::seconds seconds_type;
As for me these two typedefs are completely unnecessary.

2017-03-03 14:30 UTC, 3Hren commented on include/metrics/accumulator/decaying/exponentially.hpp
> +    typedef std::pair<double, sample_type> priority_sample_type;
Use struct instead to avoid `.first` and `.second`.

2017-03-03 14:30 UTC, 3Hren commented on include/metrics/accumulator/decaying/exponentially.hpp
> +    typedef decltype(uniform_dist)::result_type distr_real_type;
Avoid decltypes for easily deductible contexts.

2017-03-03 14:30 UTC, 3Hren commented on include/metrics/accumulator/decaying/exponentially.hpp
> +    auto update(value_type value, time_point timestamp = clock_type::now()) noexcept -> void;
This can throw actually.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +exponentially_t::exponentially_t(std::size_t sz, double al) :
Make full naming.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +auto exponentially_t::update(value_type value, time_point t) noexcept -> void {
This can throw.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +    std::unique_lock<std::mutex> lock(samples_mut);
`std::lock_guard` is sufficient here.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +auto exponentially_t::operator()(value_type value, time_point timestamp) noexcept -> void {
This can throw.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +        std::unique_lock<std::mutex> lock(samples_mut);
`std::lock_guard` is sufficient here.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +
Excess line.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +        decltype(samples) new_samples;
Avoid decltype here.

2017-03-03 14:30 UTC, 3Hren commented on src/accumulator/decaying/exponentially.cpp
> +        std::unique_lock<std::mutex> lock(samples_mut);
s/unique_lock/lock_guard/

2017-03-03 14:30 UTC, 3Hren commented on tests/accumulator/decaying/exponentially.cpp
> +    EXPECT_NEAR(snapshot.max(), 1000, 150);
Need more tests:
 - for rescaling.
 - to test lesser alphas / reservoir sizes.

2017-03-06 06:54 UTC, 3Hren commented
Okay, now make possible to instantiate such accumulator using factory and registry and this one is ready to be merged.

2017-03-06 15:32 UTC, karitra commented
It seems that commit 0d30b390d306caddb273ee7cf221ec681ae7a40c will introduce binary incompatibility with cocaine-plugins, in code tied on visitor_t at least.

2017-03-06 16:29 UTC, 3Hren commented
> It seems that commit 0d30b39 will introduce interface incompatibility with cocaine-plugins, in code tied on visitor_t at least.

May be provide default implementation?

2017-03-07 09:13 UTC, 3Hren commented
LGTM.

2017-03-07 10:31 UTC, karitra commented
Pls, don't merge, as still WIP. Some fixes are needed for Cocaine-plugins compatibility.

2017-03-13 11:32 UTC, 3Hren approved these changes

2017-03-13 11:33 UTC, merged