feat: instantiate ewma class with steady_clock
3Hren/metrics pull request #15
Opened 2018-05-21 09:49 UTC by shaitan

`ewma` expects that time points are monotonically increased, so `steady_clock` should be used.

2018-05-21 10:17 UTC, 3Hren requested changes

2018-05-21 10:17 UTC, 3Hren commented on debian/changelog
> +metrics (3.1.1) unstable; urgency=low
Please use `<major>.<minor>.<patch>-<release>` versioning, as it was before.

2018-05-21 10:20 UTC, shaitan commented on debian/changelog
> +metrics (3.1.1) unstable; urgency=low
`3.1.1-1` will be ok?

2018-05-22 06:38 UTC, shaitan commented
@3Hren ping

2018-05-22 15:35 UTC, 3Hren approved these changes

2018-05-22 15:36 UTC, merged